---
abstract: 'Installs missing modules on demand'
author:
  - 'Fuji, Goro (gfx) <gfuji@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: lib::xi
name: lib-xi
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::cpanminus: 0
  File::Which: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-lib-xi.git
version: 0.03
